function injectRouteImage()
{var ROUTE_IMAGE='https\u003A\/\/bigcommerce.route.com\/images\/route_logo_checkout_3.png';var ROUTE_PRODUCT_NAME='Route\u0020Package\u0020Protection';var minicartPrevIntvl=false;var mutationConfig={attributes:false,childList:true};console.log('[routeimg]','init');$(document).on('DOMSubtreeModified','aside.layout-cart',function(){setTimeout(function(){$('img[data-test="cart-item-image"]').each(function(idx,el){var alt=$(el).attr('alt');if(alt===ROUTE_PRODUCT_NAME){$(el).attr('src',ROUTE_IMAGE);}})},0);});$(document).ready(function(){setTimeout(function(){var targetNodes=document.getElementsByClassName('ReactModalPortal');var callback=function(mutationsList){for(var mutation of mutationsList){if(mutation.type=='childList'){setTimeout(function(){$('li.productList-item').each(function(idx,el){if($(el).find('h5.product-title').length){var t=$(el).find('h5.product-title').text()+"";if(t.indexOf(ROUTE_PRODUCT_NAME)>-1){var i=document.createElement('img');i.src=ROUTE_IMAGE;i.alt=ROUTE_PRODUCT_NAME
$(i).data('test','cart-item-image')
$(el).find('figure.product-figure').html(i);}}});},0);}
else if(mutation.type=='attributes'){}}};var observer=new MutationObserver(callback);$(targetNodes).each(function(idx,el){observer.observe(el,mutationConfig);});},1200);$('.CartContents tr').each(function(idx,el){if($(el).text().indexOf('Route Shipping')>-1){var img=document.createElement("img");img.src=ROUTE_IMAGE;img.style="width: 150px;";$(el).find('.CartThumb').css('text-align','center');$(el).find('.CartThumb').html(img);}});});function handleMinicart(){$(document).on('click','.navUser-item--cart',function(e){if(minicartPrevIntvl){clearInterval(minicartPrevIntvl);minicartPrevIntvl=false;}
minicartPrevIntvl=setInterval(function(){var type='preview';var nodeType='dropdown';var cartNodes=$('#cart-preview-'+nodeType);$('.'+type+'CartItem').each(function(idx,el){if($(el).find('h6.'+type+'CartItem-name').length){var t=$(el).find('h6.'+type+'CartItem-name').text()+"";if(t.indexOf(ROUTE_PRODUCT_NAME)>-1){var i=$(el).find('.'+type+'CartItem-image img');if(i.length){setTimeout(function(){$(i).attr('src',ROUTE_IMAGE);},0);}}}
if($(el).find('div.'+type+'CartItem-name h6')){var t=$(el).find('div.'+type+'CartItem-name h6').text()+"";if(t.indexOf(ROUTE_PRODUCT_NAME)>-1){var i=$(el).find('.'+type+'CartItem-image img');if(i.length){setTimeout(function(){$(i).attr('src',ROUTE_IMAGE);},0);}}}});},200);setTimeout(function(){var type='offcanvas';var nodeType='offcanvas';var cartNodes=$('#cart-preview-'+nodeType);$('.'+type+'CartItem').each(function(idx,el){if($(el).find('h6.'+type+'CartItem-name').length){var t=$(el).find('h6.'+type+'CartItem-name').text()+"";if(t.indexOf(ROUTE_PRODUCT_NAME)>-1){var i=$(el).find('.'+type+'CartItem-image img');if(i.length){$(i).attr('src',ROUTE_IMAGE);}}}
if($(el).find('div.'+type+'CartItem-name h6')){var t=$(el).find('div.'+type+'CartItem-name h6').text()+"";if(t.indexOf(ROUTE_PRODUCT_NAME)>-1){var i=$(el).find('.'+type+'CartItem-image img');if(i.length){$(i).attr('src',ROUTE_IMAGE);}}}});var cartImageCallbackOffcanvas=function(mutationsList){for(var mutation of mutationsList){if(mutation.type=='childList'){setTimeout(function(){$('.'+type+'CartItem').each(function(idx,el){if($(el).find('h6.'+type+'CartItem-name').length){var t=$(el).find('h6.'+type+'CartItem-name a').text()+"";if(t.indexOf(ROUTE_PRODUCT_NAME)>-1){var i=$(el).find('.'+type+'CartItem-image img');if(i.length){$(i).attr('src',ROUTE_IMAGE);}}}
if($(el).find('div.'+type+'CartItem-name h6')){var t=$(el).find('div.'+type+'CartItem-name h6 a').text()+"";if(t.indexOf(ROUTE_PRODUCT_NAME)>-1){var i=$(el).find('.'+type+'CartItem-image img');if(i.length){$(i).attr('src',ROUTE_IMAGE);}}}});},0);}else if(mutation.type=='attributes'){}}};var observer=new MutationObserver(cartImageCallbackOffcanvas);$(cartNodes).each(function(idx,el){observer.observe(el,mutationConfig);});},0);});}
function handleCartPage(){if($('table.cart').length){$('table.cart tbody tr.cart-item').each(function(idx,el){var t=$(el).find('h4.cart-item-name a').text();if(t===ROUTE_PRODUCT_NAME){var i=$(el).find('img.cart-item-image');if(i.length){if($(i).attr('src')!==ROUTE_IMAGE){$(i).attr('src',ROUTE_IMAGE);}}}});}}
$(document).ready(function(){handleCartPage();handleMinicart();if(document.location.pathname==='/cart.php'){setInterval(function(){handleCartPage()},100);}});}
function initRouteImage(){if(typeof $==="undefined"){javascript:(function(){function l(u,i,cb=null){var d=document;if(!d.getElementById(i)){var s=d.createElement('script');s.src=u;s.id=i;if(typeof cb==="function"){s.onload=function(){cb();};}
d.body.appendChild(s);}}
l('//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js','jquery',injectRouteImage)})();}else{injectRouteImage();}}
initRouteImage();